# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
UserGroup.create(group_name: "admin")
UserGroup.create(group_name: "staff")
UserGroup.create(group_name: "customer")
admin_group = UserGroup.find_by group_name: "admin"
staff_group = UserGroup.find_by group_name: "staff"

User.create(email: "admin@admin.admin", username: "admin", password: "admin", user_group_id: admin_group.id)
User.create(email: "staff@staff.staff", username: "staff", password: "staff", user_group_id: staff_group.id)

Filament.create(description: "ABS White", hex_color_value: "0xAAAAAA", price_per_gram: "1", remaining: "1000")
Filament.create(description: "ABS Black", hex_color_value: "0x111111", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA White", hex_color_value: "0xAAAAAA", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Black", hex_color_value: "0x111111", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Pink", hex_color_value: "0xC879CE", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Salmon", hex_color_value: "0xED8B9C", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Green", hex_color_value: "0x9FED9C", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Blue", hex_color_value: "0x5AEDE0", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Purple", hex_color_value: "0x8364BC", price_per_gram: "1", remaining: "1000")
Filament.create(description: "PLA Orange", hex_color_value: "0xd17947", price_per_gram: "1", remaining: "1000")

PrintSpeed.create(configuration: "ธรรมดา")
PrintSpeed.create(configuration: "ด่วน")

PostalCode.create(number_code: "10100", city: "Samphanthawong", province: "Bangkok")
PostalCode.create(number_code: "10110", city: "Wattana", province: "Bangkok")
PostalCode.create(number_code: "10120", city: "Bang Kholame", province: "Bangkok")
PostalCode.create(number_code: "10140", city: "Thung Khru", province: "Bangkok")
PostalCode.create(number_code: "10150", city: "Bang Bon", province: "Bangkok")
PostalCode.create(number_code: "10160", city: "Nong Khaem", province: "Bangkok")
PostalCode.create(number_code: "10170", city: "Thawi Wattana", province: "Bangkok")
PostalCode.create(number_code: "10200", city: "Phra Nakhon", province: "Bangkok")
PostalCode.create(number_code: "10210", city: "Lak Si", province: "Bangkok")
PostalCode.create(number_code: "10220", city: "Sai Mai", province: "Bangkok")
PostalCode.create(number_code: "10230", city: "Lat Phrao", province: "Bangkok")
PostalCode.create(number_code: "10240", city: "Saphan Sung B39", province: "Bangkok")
PostalCode.create(number_code: "10250", city: "Pra Vet", province: "Bangkok")
PostalCode.create(number_code: "10260", city: "Phra Khanong", province: "Bangkok")
PostalCode.create(number_code: "10300", city: "Dusit", province: "Bangkok")
PostalCode.create(number_code: "10310", city: "Wangthong Lang", province: "Bangkok")
PostalCode.create(number_code: "10320", city: "Huai Khwang", province: "Bangkok")
PostalCode.create(number_code: "10330", city: "Pahtum Wan", province: "Bangkok")
PostalCode.create(number_code: "10400", city: "Ding Daeng", province: "Bangkok")
PostalCode.create(number_code: "10500", city: "Bang Rak", province: "Bangkok")
PostalCode.create(number_code: "10510", city: "Khlong Samwa", province: "Bangkok")
PostalCode.create(number_code: "10520", city: "Lat Krabang", province: "Bangkok")
PostalCode.create(number_code: "10530", city: "Nong Chok", province: "Bangkok")
PostalCode.create(number_code: "10600", city: "Thon Buri", province: "Bangkok")
PostalCode.create(number_code: "10700", city: "Bangkok Noi", province: "Bangkok")
PostalCode.create(number_code: "10800", city: "Bang Su", province: "Bangkok")
PostalCode.create(number_code: "10130", city: "Phra Pradaeng", province: "Samut Prakan")
PostalCode.create(number_code: "10270", city: "Muang Samut Prakan", province: "Samut Prakan")
PostalCode.create(number_code: "10290", city: "Phra Samut Chedi", province: "Samut Prakan")
PostalCode.create(number_code: "10540", city: "Bang Saotong", province: "Samut Prakan")
PostalCode.create(number_code: "10560", city: "Bang Bo", province: "Samut Prakan")
PostalCode.create(number_code: "11000", city: "Muang Nonthaburi", province: "Nonthaburi")
PostalCode.create(number_code: "11110", city: "Bang Bua Thong", province: "Nonthaburi")
PostalCode.create(number_code: "11120", city: "Pak Kret", province: "Nonthaburi")
PostalCode.create(number_code: "11130", city: "Bang Kruai", province: "Nonthaburi")
PostalCode.create(number_code: "11140", city: "Bang Yai", province: "Nonthaburi")
PostalCode.create(number_code: "11150", city: "Sai Noi", province: "Nonthaburi")
PostalCode.create(number_code: "12000", city: "Muang Pathum Thani", province: "Pathum Thani")
PostalCode.create(number_code: "12110", city: "Thanyaburi", province: "Pathum Thani")
PostalCode.create(number_code: "12120", city: "Khlong Luang", province: "Pathum Thani")
PostalCode.create(number_code: "12140", city: "Lat Lum Kaeo", province: "Pathum Thani")
PostalCode.create(number_code: "12150", city: "Lam Luk Ka", province: "Pathum Thani")
PostalCode.create(number_code: "12160", city: "Sam Khok", province: "Pathum Thani")
PostalCode.create(number_code: "12170", city: "Nong Sua", province: "Pathum Thani")
PostalCode.create(number_code: "14000", city: "Muang ANG THONG", province: "Ang Thong")
PostalCode.create(number_code: "14110", city: "Wiset Chai Chan", province: "Ang Thong")
PostalCode.create(number_code: "14120", city: "Pho Thong", province: "Ang Thong")
PostalCode.create(number_code: "14130", city: "Pa Mok", province: "Ang Thong")
PostalCode.create(number_code: "14140", city: "Chaiyo", province: "Ang Thong")
PostalCode.create(number_code: "14150", city: "Sawaengha", province: "Ang Thong")
PostalCode.create(number_code: "14160", city: "Samko", province: "Ang Thong")
PostalCode.create(number_code: "18000", city: "Muang Saraburi", province: "Saraburi")
PostalCode.create(number_code: "18110", city: "Kaeng Khoi", province: "Saraburi")
PostalCode.create(number_code: "18120", city: "Phra Phutthabat", province: "Saraburi")
PostalCode.create(number_code: "18130", city: "Ban Mo", province: "Saraburi")
PostalCode.create(number_code: "18140", city: "Nong Khae", province: "Saraburi")
PostalCode.create(number_code: "18150", city: "Wihan Daeng", province: "Saraburi")
PostalCode.create(number_code: "18160", city: "Sao Hai", province: "Saraburi")
PostalCode.create(number_code: "18170", city: "Nong Saeng", province: "Saraburi")
PostalCode.create(number_code: "18180", city: "Muak Lek", province: "Saraburi")
PostalCode.create(number_code: "18190", city: "Nong Doan", province: "Saraburi")
PostalCode.create(number_code: "18210", city: "Don Phut", province: "Saraburi")
PostalCode.create(number_code: "18220", city: "Wang Muang", province: "Saraburi")
PostalCode.create(number_code: "21000", city: "Muang Rayong", province: "Rayong")
PostalCode.create(number_code: "21110", city: "Khao Chamao", province: "Rayong")
PostalCode.create(number_code: "21120", city: "Ban Khai", province: "Rayong")
PostalCode.create(number_code: "21130", city: "Ban Chang", province: "Rayong")
PostalCode.create(number_code: "21140", city: "Pluak Daeng", province: "Rayong")
PostalCode.create(number_code: "21180", city: "Nikhom Pattana", province: "Rayong")
PostalCode.create(number_code: "21210", city: "Wang Chan", province: "Rayong")
PostalCode.create(number_code: "22000", city: "Muang Chanthaburi", province: "Chanthaburi")
PostalCode.create(number_code: "22110", city: "Khlung", province: "Chanthaburi")
PostalCode.create(number_code: "22120", city: "Tha Mai", province: "Chanthaburi")
PostalCode.create(number_code: "22130", city: "Laem Sing", province: "Chanthaburi")
PostalCode.create(number_code: "22140", city: "Pong Nam Ron", province: "Chanthaburi")
PostalCode.create(number_code: "22150", city: "Makham", province: "Chanthaburi")
PostalCode.create(number_code: "22160", city: "Na Yai Am", province: "Chanthaburi")
PostalCode.create(number_code: "22180", city: "Soi Dao", province: "Chanthaburi")
PostalCode.create(number_code: "22210", city: "Khao Kitchakut", province: "Chanthaburi")
PostalCode.create(number_code: "23000", city: "Muang Trat", province: "Trat")
PostalCode.create(number_code: "23110", city: "Khlong Yai", province: "Trat")
PostalCode.create(number_code: "23120", city: "Ko Chang", province: "Trat")
PostalCode.create(number_code: "23130", city: "Khao Saming", province: "Trat")
PostalCode.create(number_code: "23140", city: "Bo Rai", province: "Trat")
PostalCode.create(number_code: "24000", city: "Khlong Kaen", province: "Chachoengsao")
PostalCode.create(number_code: "24110", city: "Bang Khla", province: "Chachoengsao")
PostalCode.create(number_code: "24120", city: "Rachsan", province: "Chachoengsao")
PostalCode.create(number_code: "24130", city: "Bang Pakong", province: "Chachoengsao")
PostalCode.create(number_code: "24140", city: "Ban Pho", province: "Chachoengsao")
PostalCode.create(number_code: "24150", city: "Bang Nam Prieo", province: "Chachoengsao")
PostalCode.create(number_code: "24160", city: "Sanam Chai Khet", province: "Chachoengsao")
PostalCode.create(number_code: "24190", city: "Paeng Yao", province: "Chachoengsao")
PostalCode.create(number_code: "26000", city: "Muang Nakhon Nayok", province: "Nakhon Nayok")
PostalCode.create(number_code: "26110", city: "Ban Na", province: "Nakhon Nayok")
PostalCode.create(number_code: "26120", city: "Ongkarak", province: "Nakhon Nayok")
PostalCode.create(number_code: "26130", city: "Pak Phli", province: "Nakhon Nayok")
PostalCode.create(number_code: "27000", city: "Muang Sa Kaeo", province: "Sa Kaeo")
PostalCode.create(number_code: "27120", city: "Wang Nam Yen", province: "Sa Kaeo")
PostalCode.create(number_code: "27160", city: "Wattana Nakhon", province: "Sa Kaeo")
PostalCode.create(number_code: "27180", city: "Ta Phraya", province: "Sa Kaeo")
PostalCode.create(number_code: "27250", city: "Wang Sombun", province: "Sa Kaeo")
PostalCode.create(number_code: "27260", city: "Khlong Hat", province: "Sa Kaeo")
PostalCode.create(number_code: "30000", city: "Muang Nakhon Ratchasima", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30110", city: "Phimai", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30120", city: "Bua Lai", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30130", city: "Pak Chong", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30140", city: "Sikhiu", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30150", city: "Pak Thong Chai", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30160", city: "Non Sung", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30170", city: "Sung Noen", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30180", city: "Prathai", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30190", city: "Chok Chai", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30210", city: "Theparak", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30220", city: "Non Thai", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30230", city: "Cheleam Phakiat", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30240", city: "Huai Thalaeng", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30250", city: "Khon Buri", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30260", city: "Khong", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30270", city: "Chum Phuang", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30280", city: "Kham Thale So", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30290", city: "Kham Sakae Saeng", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30330", city: "Soeng Sang", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30350", city: "Ban Luam", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30360", city: "Non Daeng", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30370", city: "Wang Nam Khyo", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30410", city: "Nong Bunnak", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30430", city: "Sida", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "30440", city: "Kang Sanam Nang", province: "Nakhon Ratchasima")
PostalCode.create(number_code: "34000", city: "Don Moddang", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34140", city: "Muang Samsib", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34150", city: "Khuang Nai", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34160", city: "Det Udom", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34170", city: "Khemarat", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34220", city: "Khong Chiam", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34230", city: "Buntharik", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34270", city: "Kut Khaopun", province: "Ubon Ratchathani")
PostalCode.create(number_code: "34280", city: "Na Chaluai", province: "Ubon Ratchathani")
PostalCode.create(number_code: "35000", city: "Muang Yasothon", province: "Yasothon")
PostalCode.create(number_code: "35110", city: "Kham Khuan Kaeo", province: "Yasothon")
PostalCode.create(number_code: "35120", city: "Loeng Nok Tha", province: "Yasothon")
PostalCode.create(number_code: "35130", city: "Maha Chana Chai", province: "Yasothon")
PostalCode.create(number_code: "35140", city: "Kud Chum", province: "Yasothon")
PostalCode.create(number_code: "35150", city: "Pa Tiu", province: "Yasothon")
PostalCode.create(number_code: "35160", city: "Kho Wang", province: "Yasothon")
PostalCode.create(number_code: "35170", city: "Sai Mun", province: "Yasothon")
PostalCode.create(number_code: "36000", city: "Muang Chaiyaphum", province: "Chaiyaphum")
PostalCode.create(number_code: "36110", city: "Phu Khieo", province: "Chaiyaphum")
PostalCode.create(number_code: "36120", city: "Kaset Sombun", province: "Chaiyaphum")
PostalCode.create(number_code: "36130", city: "Sub Yai", province: "Chaiyaphum")
PostalCode.create(number_code: "36140", city: "Khon Sawan", province: "Chaiyaphum")
PostalCode.create(number_code: "36150", city: "Kaeng Khro", province: "Chaiyaphum")
PostalCode.create(number_code: "36160", city: "Bamnet Narong", province: "Chaiyaphum")
PostalCode.create(number_code: "36170", city: "Ban Khwao", province: "Chaiyaphum")
PostalCode.create(number_code: "36180", city: "Khon San", province: "Chaiyaphum")
PostalCode.create(number_code: "36190", city: "Ban Thaen", province: "Chaiyaphum")
PostalCode.create(number_code: "36210", city: "Nong Bua Daeng", province: "Chaiyaphum")
PostalCode.create(number_code: "36230", city: "Thep Satthit", province: "Chaiyaphum")
PostalCode.create(number_code: "36250", city: "Nong Bua Rawe", province: "Chaiyaphum")
PostalCode.create(number_code: "36260", city: "Phakdi Chumpon", province: "Chaiyaphum")
PostalCode.create(number_code: "37000", city: "Lua Amnart", province: "Amnat Charoen")
PostalCode.create(number_code: "37110", city: "Phathumratvongsa", province: "Amnat Charoen")
PostalCode.create(number_code: "37180", city: "Phana", province: "Amnat Charoen")
PostalCode.create(number_code: "37210", city: "Chanunman", province: "Amnat Charoen")
PostalCode.create(number_code: "37240", city: "Hua Taphan", province: "Amnat Charoen")
PostalCode.create(number_code: "37290", city: "Senangkhanikhorn", province: "Amnat Charoen")
PostalCode.create(number_code: "40000", city: "Muang Khonkaen", province: "Khon Kaen")
PostalCode.create(number_code: "40110", city: "Ban Had", province: "Khon Kaen")
PostalCode.create(number_code: "40120", city: "Phon", province: "Khon Kaen")
PostalCode.create(number_code: "40130", city: "Chum Phae", province: "Khon Kaen")
PostalCode.create(number_code: "40140", city: "Nam Phong", province: "Khon Kaen")
PostalCode.create(number_code: "40150", city: "Nong Nakham", province: "Khon Kaen")
PostalCode.create(number_code: "40160", city: "Khok Phochai", province: "Khon Kaen")
PostalCode.create(number_code: "40170", city: "Sum Sung", province: "Khon Kaen")
PostalCode.create(number_code: "40180", city: "Chonnabot", province: "Khon Kaen")
PostalCode.create(number_code: "40190", city: "Nong Song Hong", province: "Khon Kaen")
PostalCode.create(number_code: "40210", city: "Nong Rua", province: "Khon Kaen")
PostalCode.create(number_code: "40220", city: "Si Chomphu", province: "Khon Kaen")
PostalCode.create(number_code: "40230", city: "Waeng Noi", province: "Khon Kaen")
PostalCode.create(number_code: "40250", city: "Ubolratana", province: "Khon Kaen")
PostalCode.create(number_code: "40270", city: "Ban Fang", province: "Khon Kaen")
PostalCode.create(number_code: "40280", city: "Khao Suan Kwang", province: "Khon Kaen")
PostalCode.create(number_code: "40320", city: "Phra Yun", province: "Khon Kaen")
PostalCode.create(number_code: "40330", city: "Waeng Yai", province: "Khon Kaen")
PostalCode.create(number_code: "40340", city: "Puai Noi", province: "Khon Kaen")
PostalCode.create(number_code: "40350", city: "Phu Pha Man", province: "Khon Kaen")
PostalCode.create(number_code: "41000", city: "Muang Udon Thani", province: "Udon Thani")
PostalCode.create(number_code: "41110", city: "Phrachuk Siliakram", province: "Udon Thani")
PostalCode.create(number_code: "41130", city: "Pibun Rak", province: "Udon Thani")
PostalCode.create(number_code: "41150", city: "Phen", province: "Udon Thani")
PostalCode.create(number_code: "41190", city: "Ban Dung", province: "Udon Thani")
PostalCode.create(number_code: "41210", city: "Nam Som", province: "Udon Thani")
PostalCode.create(number_code: "41220", city: "Nong Wua So", province: "Udon Thani")
PostalCode.create(number_code: "41230", city: "Si That", province: "Udon Thani")
PostalCode.create(number_code: "41240", city: "Non Sa-at", province: "Udon Thani")
PostalCode.create(number_code: "41250", city: "Kut Chab", province: "Udon Thani")
PostalCode.create(number_code: "41260", city: "Sang Khom", province: "Udon Thani")
PostalCode.create(number_code: "41290", city: "Chaiwan", province: "Udon Thani")
PostalCode.create(number_code: "41310", city: "Thung Fon", province: "Udon Thani")
PostalCode.create(number_code: "41340", city: "Nong Saeng", province: "Udon Thani")
PostalCode.create(number_code: "41380", city: "Na Yung", province: "Udon Thani")
PostalCode.create(number_code: "42000", city: "Muang Loei", province: "Loei")
PostalCode.create(number_code: "42110", city: "Chiang Khan", province: "Loei")
PostalCode.create(number_code: "42120", city: "Dan Sai", province: "Loei")
PostalCode.create(number_code: "42130", city: "Wang Saphung", province: "Loei")
PostalCode.create(number_code: "42140", city: "Tha Li", province: "Loei")
PostalCode.create(number_code: "42150", city: "Pak Chom", province: "Loei")
PostalCode.create(number_code: "42160", city: "Phu Rua", province: "Loei")
PostalCode.create(number_code: "42170", city: "Na Haeo", province: "Loei")
PostalCode.create(number_code: "42180", city: "Phu Kradung", province: "Loei")
PostalCode.create(number_code: "42210", city: "Na Duang", province: "Loei")
PostalCode.create(number_code: "42230", city: "Phu Luang", province: "Loei")
PostalCode.create(number_code: "42240", city: "Pha Khao", province: "Loei")
PostalCode.create(number_code: "43000", city: "Muang Nong Khai", province: "Nong Khai")
PostalCode.create(number_code: "43100", city: "Sra Khai", province: "Nong Khai")
PostalCode.create(number_code: "43110", city: "Tha Bo", province: "Nong Khai")
PostalCode.create(number_code: "43120", city: "Phon Phisai", province: "Nong Khai")
PostalCode.create(number_code: "43130", city: "Po Tak", province: "Nong Khai")
PostalCode.create(number_code: "43140", city: "Bung Kla", province: "Nong Khai")
PostalCode.create(number_code: "43150", city: "Seka", province: "Nong Khai")
PostalCode.create(number_code: "43160", city: "Sang Khom", province: "Nong Khai")
PostalCode.create(number_code: "43170", city: "So Phisai", province: "Nong Khai")
PostalCode.create(number_code: "43180", city: "Phon Charoen", province: "Nong Khai")
PostalCode.create(number_code: "43190", city: "Pak Khat", province: "Nong Khai")
PostalCode.create(number_code: "43210", city: "Si Wilai", province: "Nong Khai")
PostalCode.create(number_code: "43220", city: "Bung Khong Long", province: "Nong Khai")
PostalCode.create(number_code: "44000", city: "Muang Maha Sarakham", province: "Maha Sarakham")
PostalCode.create(number_code: "44110", city: "Phayakkhaphum Phisai", province: "Maha Sarakham")
PostalCode.create(number_code: "44120", city: "Wapi Pathum", province: "Maha Sarakham")
PostalCode.create(number_code: "44130", city: "Borabu", province: "Maha Sarakham")
PostalCode.create(number_code: "44140", city: "Kosum Phisai", province: "Maha Sarakham")
PostalCode.create(number_code: "44150", city: "Kantharawichai", province: "Maha Sarakham")
PostalCode.create(number_code: "44160", city: "Chuan Chum", province: "Maha Sarakham")
PostalCode.create(number_code: "44170", city: "Na Chuak", province: "Maha Sarakham")
PostalCode.create(number_code: "44180", city: "Na Dun", province: "Maha Sarakham")
PostalCode.create(number_code: "44190", city: "Kae Dam", province: "Maha Sarakham")
PostalCode.create(number_code: "44210", city: "Yang Si Surat", province: "Maha Sarakham")
PostalCode.create(number_code: "45000", city: "Chang Han", province: "Roi Et")
PostalCode.create(number_code: "45110", city: "Phon Thong", province: "Roi Et")
PostalCode.create(number_code: "45120", city: "Salaphum", province: "Roi Et")
PostalCode.create(number_code: "45130", city: "Suwannaphum", province: "Roi Et")
PostalCode.create(number_code: "45140", city: "Nong Hi", province: "Roi Et")
PostalCode.create(number_code: "45150", city: "Kaset Wisai", province: "Roi Et")
PostalCode.create(number_code: "45160", city: "At Samat", province: "Roi Et")
PostalCode.create(number_code: "45170", city: "Thawatchaburi", province: "Roi Et")
PostalCode.create(number_code: "45180", city: "Chaturaphak Phiman", province: "Roi Et")
PostalCode.create(number_code: "45190", city: "Pathum Rat", province: "Roi Et")
PostalCode.create(number_code: "45210", city: "Nong Phok", province: "Roi Et")
PostalCode.create(number_code: "45220", city: "Muang Suang", province: "Roi Et")
PostalCode.create(number_code: "45230", city: "Pho Chai", province: "Roi Et")
PostalCode.create(number_code: "45240", city: "Phon Sai", province: "Roi Et")
PostalCode.create(number_code: "45250", city: "Moeiyawadi", province: "Roi Et")
PostalCode.create(number_code: "46000", city: "Muang Kalasin", province: "Kalasin")
PostalCode.create(number_code: "46110", city: "Kuchinarai", province: "Kalasin")
PostalCode.create(number_code: "46120", city: "Yang Talat", province: "Kalasin")
PostalCode.create(number_code: "46130", city: "Kamalasai", province: "Kalasin")
PostalCode.create(number_code: "46140", city: "Sahatsakhan", province: "Kalasin")
PostalCode.create(number_code: "46150", city: "Somdet", province: "Kalasin")
PostalCode.create(number_code: "46160", city: "Khao Wong", province: "Kalasin")
PostalCode.create(number_code: "46170", city: "Huai Mek", province: "Kalasin")
PostalCode.create(number_code: "46180", city: "Kham Muang", province: "Kalasin")
PostalCode.create(number_code: "46190", city: "Tha Khantho", province: "Kalasin")
PostalCode.create(number_code: "46210", city: "Rong Kham", province: "Kalasin")
PostalCode.create(number_code: "46220", city: "Nong Kung Si", province: "Kalasin")
PostalCode.create(number_code: "46230", city: "Na Mon", province: "Kalasin")
PostalCode.create(number_code: "46240", city: "Huai Phung", province: "Kalasin")
PostalCode.create(number_code: "47000", city: "Muang Sakon Nakhon", province: "Sakon Nakhon")
PostalCode.create(number_code: "47110", city: "Sawang Daen Din", province: "Sakon Nakhon")
PostalCode.create(number_code: "47120", city: "Wanon Niwat", province: "Sakon Nakhon")
PostalCode.create(number_code: "47130", city: "Phanna Nikhom", province: "Sakon Nakhon")
PostalCode.create(number_code: "47140", city: "Ban Muang", province: "Sakon Nakhon")
PostalCode.create(number_code: "47150", city: "Waritchaphum", province: "Sakon Nakhon")
PostalCode.create(number_code: "47160", city: "Phang Khon", province: "Sakon Nakhon")
PostalCode.create(number_code: "47170", city: "Akat Amnuai", province: "Sakon Nakhon")
PostalCode.create(number_code: "47180", city: "Phu Phan", province: "Sakon Nakhon")
PostalCode.create(number_code: "47190", city: "Song Dao", province: "Sakon Nakhon")
PostalCode.create(number_code: "47210", city: "Kusuman", province: "Sakon Nakhon")
PostalCode.create(number_code: "47230", city: "Pon Nakaew", province: "Sakon Nakhon")
PostalCode.create(number_code: "47250", city: "Kham Ta Kla", province: "Sakon Nakhon")
PostalCode.create(number_code: "47260", city: "Tao Ngoi", province: "Sakon Nakhon")
PostalCode.create(number_code: "47270", city: "Nikhom Nam Un", province: "Sakon Nakhon")
PostalCode.create(number_code: "47280", city: "Khok Si Supan", province: "Sakon Nakhon")
PostalCode.create(number_code: "47290", city: "Charoensin", province: "Sakon Nakhon")
PostalCode.create(number_code: "48000", city: "Muang Nakhon Phanom", province: "Nakhon Phanom")
PostalCode.create(number_code: "48110", city: "That Phanom", province: "Nakhon Phanom")
PostalCode.create(number_code: "48120", city: "Tha Uthen", province: "Nakhon Phanom")
PostalCode.create(number_code: "48130", city: "Wang Yang", province: "Nakhon Phanom")
PostalCode.create(number_code: "48140", city: "Na Thom", province: "Nakhon Phanom")
PostalCode.create(number_code: "48150", city: "Si Songkhram", province: "Nakhon Phanom")
PostalCode.create(number_code: "48160", city: "Pla Pak", province: "Nakhon Phanom")
PostalCode.create(number_code: "48170", city: "Renu Nakhon", province: "Nakhon Phanom")
PostalCode.create(number_code: "48180", city: "Na Wa", province: "Nakhon Phanom")
PostalCode.create(number_code: "48190", city: "Phon Sawan", province: "Nakhon Phanom")
PostalCode.create(number_code: "49000", city: "Muang Mukdahan", province: "Mukdahan")
PostalCode.create(number_code: "49110", city: "Khamcha-I", province: "Mukdahan")
PostalCode.create(number_code: "49120", city: "Don Tan", province: "Mukdahan")
PostalCode.create(number_code: "49130", city: "Nikhom Kham Soi", province: "Mukdahan")
PostalCode.create(number_code: "49140", city: "Don Luang", province: "Mukdahan")
PostalCode.create(number_code: "49150", city: "Wan Yai", province: "Mukdahan")
PostalCode.create(number_code: "49160", city: "Nong Sung", province: "Mukdahan")
PostalCode.create(number_code: "50000", city: "Muang Chiang Mai", province: "Chiang Mai")
PostalCode.create(number_code: "50110", city: "Fang", province: "Chiang Mai")
PostalCode.create(number_code: "50120", city: "San Pa Tong", province: "Chiang Mai")
PostalCode.create(number_code: "50130", city: "San Kamphaeng", province: "Chiang Mai")
PostalCode.create(number_code: "50140", city: "Saraphi", province: "Chiang Mai")
PostalCode.create(number_code: "50150", city: "Mae Taeng", province: "Chiang Mai")
PostalCode.create(number_code: "50160", city: "Doi Lor", province: "Chiang Mai")
PostalCode.create(number_code: "50170", city: "Chiang Dao", province: "Chiang Mai")
PostalCode.create(number_code: "50180", city: "Mae Rim", province: "Chiang Mai")
PostalCode.create(number_code: "50190", city: "Phrao", province: "Chiang Mai")
PostalCode.create(number_code: "50210", city: "San Sai", province: "Chiang Mai")
PostalCode.create(number_code: "50220", city: "Doi Saket", province: "Chiang Mai")
PostalCode.create(number_code: "50230", city: "Hang Dong", province: "Chiang Mai")
PostalCode.create(number_code: "50240", city: "Hot", province: "Chiang Mai")
PostalCode.create(number_code: "50250", city: "Samoeng", province: "Chiang Mai")
PostalCode.create(number_code: "50260", city: "Doi Tao", province: "Chiang Mai")
PostalCode.create(number_code: "50270", city: "Mae Chaem", province: "Chiang Mai")
PostalCode.create(number_code: "50280", city: "Mae Ai", province: "Chiang Mai")
PostalCode.create(number_code: "50310", city: "Omkoi", province: "Chiang Mai")
PostalCode.create(number_code: "50320", city: "Chai Prakarn", province: "Chiang Mai")
PostalCode.create(number_code: "50350", city: "Weang Hang", province: "Chiang Mai")
PostalCode.create(number_code: "50360", city: "Mae Wang", province: "Chiang Mai")
PostalCode.create(number_code: "51000", city: "Muang Lamphun", province: "Lamphun")
PostalCode.create(number_code: "51110", city: "Li", province: "Lamphun")
PostalCode.create(number_code: "51120", city: "Pa Sang", province: "Lamphun")
PostalCode.create(number_code: "51130", city: "Ban Hong", province: "Lamphun")
PostalCode.create(number_code: "51140", city: "Mae Tha", province: "Lamphun")
PostalCode.create(number_code: "51160", city: "Thung Hua Chang", province: "Lamphun")
PostalCode.create(number_code: "51180", city: "Ban Thi", province: "Lamphun")
PostalCode.create(number_code: "52000", city: "Muang Lampang", province: "Lampang")
PostalCode.create(number_code: "52110", city: "Ngao", province: "Lampang")
PostalCode.create(number_code: "52120", city: "Chae Hom", province: "Lampang")
PostalCode.create(number_code: "52130", city: "Ko Kha", province: "Lampang")
PostalCode.create(number_code: "52140", city: "Wang Nua", province: "Lampang")
PostalCode.create(number_code: "52150", city: "Mae Tha", province: "Lampang")
PostalCode.create(number_code: "52160", city: "Thoen", province: "Lampang")
PostalCode.create(number_code: "52170", city: "Sop Prap", province: "Lampang")
PostalCode.create(number_code: "52180", city: "Mae Phrik", province: "Lampang")
PostalCode.create(number_code: "52190", city: "Hang Chat", province: "Lampang")
PostalCode.create(number_code: "52210", city: "Soem Ngam", province: "Lampang")
PostalCode.create(number_code: "52220", city: "Mae Mo", province: "Lampang")
PostalCode.create(number_code: "52240", city: "Muang Pan", province: "Lampang")
PostalCode.create(number_code: "53000", city: "Muang Uttaradit", province: "Uttaradit")
PostalCode.create(number_code: "53110", city: "Nam Pat", province: "Uttaradit")
PostalCode.create(number_code: "53120", city: "Phichai", province: "Uttaradit")
PostalCode.create(number_code: "53130", city: "Laplae", province: "Uttaradit")
PostalCode.create(number_code: "53140", city: "Tron", province: "Uttaradit")
PostalCode.create(number_code: "53150", city: "Tha Pla", province: "Uttaradit")
PostalCode.create(number_code: "53160", city: "Fak Tha", province: "Uttaradit")
PostalCode.create(number_code: "53180", city: "Ban Khok", province: "Uttaradit")
PostalCode.create(number_code: "53230", city: "Tong Saen Khan", province: "Uttaradit")
PostalCode.create(number_code: "54000", city: "Muang Phrae", province: "Phrae")
PostalCode.create(number_code: "54120", city: "Song", province: "Phrae")
PostalCode.create(number_code: "54130", city: "Sung Men", province: "Phrae")
PostalCode.create(number_code: "54140", city: "Den Chai", province: "Phrae")
PostalCode.create(number_code: "54150", city: "Long", province: "Phrae")
PostalCode.create(number_code: "54160", city: "Wang Chin", province: "Phrae")
PostalCode.create(number_code: "54170", city: "Nong Muangkhai", province: "Phrae")
PostalCode.create(number_code: "55000", city: "Phu Piang", province: "Nan")
PostalCode.create(number_code: "55110", city: "Wiang Sa", province: "Nan")
PostalCode.create(number_code: "55120", city: "Pua", province: "Nan")
PostalCode.create(number_code: "55130", city: "Thung Chang", province: "Nan")
PostalCode.create(number_code: "55140", city: "Tha Wang Pha", province: "Nan")
PostalCode.create(number_code: "55150", city: "Na Noi", province: "Nan")
PostalCode.create(number_code: "55160", city: "Song Khaew", province: "Nan")
PostalCode.create(number_code: "55170", city: "Mae Charim", province: "Nan")
PostalCode.create(number_code: "55180", city: "Na Mun", province: "Nan")
PostalCode.create(number_code: "55190", city: "Ban Luang", province: "Nan")
PostalCode.create(number_code: "55220", city: "Bo Klua", province: "Nan")
PostalCode.create(number_code: "56000", city: "Muang Phayao", province: "Phayao")
PostalCode.create(number_code: "56110", city: "Chiang Kham", province: "Phayao")
PostalCode.create(number_code: "56120", city: "Dok Kham Tai", province: "Phayao")
PostalCode.create(number_code: "56130", city: "Mae Chai", province: "Phayao")
PostalCode.create(number_code: "56140", city: "Pong", province: "Phayao")
PostalCode.create(number_code: "56150", city: "Chun", province: "Phayao")
PostalCode.create(number_code: "56160", city: "Chiacg Muan", province: "Phayao")
PostalCode.create(number_code: "57000", city: "Muang Chiang Rai", province: "Chiang Rai")
PostalCode.create(number_code: "57110", city: "Mae Pha Luang", province: "Chiang Rai")
PostalCode.create(number_code: "57120", city: "Phan", province: "Chiang Rai")
PostalCode.create(number_code: "57130", city: "Mae Sai", province: "Chiang Rai")
PostalCode.create(number_code: "57140", city: "Chiang Khong", province: "Chiang Rai")
PostalCode.create(number_code: "57150", city: "Chiang Saen", province: "Chiang Rai")
PostalCode.create(number_code: "57160", city: "Thoeng", province: "Chiang Rai")
PostalCode.create(number_code: "57170", city: "Wiang Pa Pao", province: "Chiang Rai")
PostalCode.create(number_code: "57180", city: "Mae Suai", province: "Chiang Rai")
PostalCode.create(number_code: "57190", city: "Pa Daet", province: "Chiang Rai")
PostalCode.create(number_code: "57210", city: "Wiang Chai", province: "Chiang Rai")
PostalCode.create(number_code: "57250", city: "Mae Lao", province: "Chiang Rai")
PostalCode.create(number_code: "57290", city: "Phaya Mengrai", province: "Chiang Rai")
PostalCode.create(number_code: "57310", city: "Wiang Kaen", province: "Chiang Rai")
PostalCode.create(number_code: "57340", city: "Khun Tan", province: "Chiang Rai")
PostalCode.create(number_code: "58000", city: "Muang Mae Hong Son", province: "Mae Hong Son")
PostalCode.create(number_code: "58110", city: "Sop Moei", province: "Mae Hong Son")
PostalCode.create(number_code: "58120", city: "Mae La Noi", province: "Mae Hong Son")
PostalCode.create(number_code: "58130", city: "Pai", province: "Mae Hong Son")
PostalCode.create(number_code: "58140", city: "Khun Yuam", province: "Mae Hong Son")
PostalCode.create(number_code: "58150", city: "Pang Mapha", province: "Mae Hong Son")
PostalCode.create(number_code: "60000", city: "Muang Nakhon Sawan", province: "Nakhon Sawan")
PostalCode.create(number_code: "60110", city: "Nong Bua", province: "Nakhon Sawan")
PostalCode.create(number_code: "60120", city: "Chumsaeng", province: "Nakhon Sawan")
PostalCode.create(number_code: "60130", city: "Phayuha Khiri", province: "Nakhon Sawan")
PostalCode.create(number_code: "60140", city: "Takhli", province: "Nakhon Sawan")
PostalCode.create(number_code: "60150", city: "Mae Wong", province: "Nakhon Sawan")
PostalCode.create(number_code: "60160", city: "Tha Tako", province: "Nakhon Sawan")
PostalCode.create(number_code: "60170", city: "Krok Phra", province: "Nakhon Sawan")
PostalCode.create(number_code: "60180", city: "Banphot Phisai", province: "Nakhon Sawan")
PostalCode.create(number_code: "60190", city: "Tak Fa", province: "Nakhon Sawan")
PostalCode.create(number_code: "60220", city: "Phaisali", province: "Nakhon Sawan")
PostalCode.create(number_code: "60230", city: "Kao Lieo", province: "Nakhon Sawan")
PostalCode.create(number_code: "61000", city: "Muang Uthai Thani", province: "Uthai Thani")
PostalCode.create(number_code: "61110", city: "Nong Chang", province: "Uthai Thani")
PostalCode.create(number_code: "61120", city: "Thap Than", province: "Uthai Thani")
PostalCode.create(number_code: "61130", city: "Nong Khayang", province: "Uthai Thani")
PostalCode.create(number_code: "61140", city: "Ban Rai", province: "Uthai Thani")
PostalCode.create(number_code: "61150", city: "Sawang Arom", province: "Uthai Thani")
PostalCode.create(number_code: "61160", city: "Lan Sak", province: "Uthai Thani")
PostalCode.create(number_code: "61170", city: "Huai Khot", province: "Uthai Thani")
PostalCode.create(number_code: "62000", city: "Muang Kamphaeng Phet", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62110", city: "Phran Kratai", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62120", city: "Khlong Khlung", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62130", city: "Khanu Woralaksaburi", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62150", city: "Sai Ngam", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62170", city: "Khosamphi Nakhon", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62180", city: "Khlong Lan", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62190", city: "Saithong Wattana", province: "Kamphaeng Phet")
PostalCode.create(number_code: "62210", city: "Bung Samakki", province: "Kamphaeng Phet")
PostalCode.create(number_code: "63000", city: "Wang Chaw", province: "Tak")
PostalCode.create(number_code: "63110", city: "Mae Sot", province: "Tak")
PostalCode.create(number_code: "63120", city: "Ban Tak", province: "Tak")
PostalCode.create(number_code: "63130", city: "Sam Ngao", province: "Tak")
PostalCode.create(number_code: "63140", city: "Mae Ramat", province: "Tak")
PostalCode.create(number_code: "63150", city: "Tha Song Yang", province: "Tak")
PostalCode.create(number_code: "63160", city: "Phob Phra", province: "Tak")
PostalCode.create(number_code: "63170", city: "Umphang", province: "Tak")
PostalCode.create(number_code: "64000", city: "Muang Sukhothai", province: "Sukhothai")
PostalCode.create(number_code: "64110", city: "Sawankhalok", province: "Sukhothai")
PostalCode.create(number_code: "64120", city: "Si Samrong", province: "Sukhothai")
PostalCode.create(number_code: "64130", city: "Si Satchanalai", province: "Sukhothai")
PostalCode.create(number_code: "64140", city: "Ban Dan Lan Hoi", province: "Sukhothai")
PostalCode.create(number_code: "64150", city: "Thung Saliam", province: "Sukhothai")
PostalCode.create(number_code: "64160", city: "Khiri Mat", province: "Sukhothai")
PostalCode.create(number_code: "64170", city: "Kong Krailat", province: "Sukhothai")
PostalCode.create(number_code: "64180", city: "Si Nakhon", province: "Sukhothai")
PostalCode.create(number_code: "65000", city: "Muang Phitsanulok", province: "Phitsanulok")
PostalCode.create(number_code: "65110", city: "Bang Krathum", province: "Phitsanulok")
PostalCode.create(number_code: "65120", city: "Nakhon Thai", province: "Phitsanulok")
PostalCode.create(number_code: "65130", city: "Wang Thong", province: "Phitsanulok")
PostalCode.create(number_code: "65140", city: "Bang Rakam", province: "Phitsanulok")
PostalCode.create(number_code: "65150", city: "Phrom Phiram", province: "Phitsanulok")
PostalCode.create(number_code: "65160", city: "Wat Bot", province: "Phitsanulok")
PostalCode.create(number_code: "65170", city: "Chat Trakan", province: "Phitsanulok")
PostalCode.create(number_code: "65190", city: "Noen Maprang", province: "Phitsanulok")
PostalCode.create(number_code: "66000", city: "Muang Phichit", province: "Phichit")
PostalCode.create(number_code: "66110", city: "Taphan Hin", province: "Phichit")
PostalCode.create(number_code: "66120", city: "Bang Mun Nak", province: "Phichit")
PostalCode.create(number_code: "66130", city: "Bung Norong", province: "Phichit")
PostalCode.create(number_code: "66140", city: "Wachirabarami", province: "Phichit")
PostalCode.create(number_code: "66150", city: "Tab Khlo", province: "Phichit")
PostalCode.create(number_code: "66160", city: "Sak Lek", province: "Phichit")
PostalCode.create(number_code: "66180", city: "Wang Sai Phun", province: "Phichit")
PostalCode.create(number_code: "66190", city: "Pho Prathap Chang", province: "Phichit")
PostalCode.create(number_code: "66210", city: "Dong Charoen", province: "Phichit")
PostalCode.create(number_code: "70000", city: "Muang Ratchaburi", province: "Ratchaburi")
PostalCode.create(number_code: "70110", city: "Ban Pong", province: "Ratchaburi")
PostalCode.create(number_code: "70120", city: "Photharam", province: "Ratchaburi")
PostalCode.create(number_code: "70130", city: "Damnoen Saduak", province: "Ratchaburi")
PostalCode.create(number_code: "70140", city: "Pak Tho", province: "Ratchaburi")
PostalCode.create(number_code: "70150", city: "Chom Bung", province: "Ratchaburi")
PostalCode.create(number_code: "70160", city: "Bang Phae", province: "Ratchaburi")
PostalCode.create(number_code: "70170", city: "Wat Phleng", province: "Ratchaburi")
PostalCode.create(number_code: "70180", city: "Suan Phung", province: "Ratchaburi")
PostalCode.create(number_code: "72000", city: "Muang Suphan Buri", province: "Suphanburi")
PostalCode.create(number_code: "72110", city: "Song Phi Nong", province: "Suphanburi")
PostalCode.create(number_code: "72120", city: "Doembang Nangbuat", province: "Suphanburi")
PostalCode.create(number_code: "72130", city: "Sam Chuk", province: "Suphanburi")
PostalCode.create(number_code: "72140", city: "Si Prachan", province: "Suphanburi")
PostalCode.create(number_code: "72150", city: "Bang Pla Ma", province: "Suphanburi")
PostalCode.create(number_code: "72160", city: "U-Thong", province: "Suphanburi")
PostalCode.create(number_code: "72170", city: "Don Chedi", province: "Suphanburi")
PostalCode.create(number_code: "72180", city: "Dan Chang", province: "Suphanburi")
PostalCode.create(number_code: "72240", city: "Nong Yasai", province: "Suphanburi")
PostalCode.create(number_code: "73000", city: "Muang Nakhon Pathom", province: "Nakhon Pathom")
PostalCode.create(number_code: "73110", city: "Sam Phran", province: "Nakhon Pathom")
PostalCode.create(number_code: "73120", city: "Nakhon Chaisi", province: "Nakhon Pathom")
PostalCode.create(number_code: "73130", city: "Bang Len", province: "Nakhon Pathom")
PostalCode.create(number_code: "73140", city: "Khamphaeng Saen", province: "Nakhon Pathom")
PostalCode.create(number_code: "73150", city: "Don Tum", province: "Nakhon Pathom")
PostalCode.create(number_code: "73170", city: "Phutha Monthon", province: "Nakhon Pathom")
PostalCode.create(number_code: "74000", city: "Muang Samut Sakhon", province: "Samut Sakhon")
PostalCode.create(number_code: "74110", city: "Krathum Baen", province: "Samut Sakhon")
PostalCode.create(number_code: "74120", city: "Ban Phaeo", province: "Samut Sakhon")
PostalCode.create(number_code: "75000", city: "Muang Samut Songkhram", province: "Samut Songkhram")
PostalCode.create(number_code: "75110", city: "Amphawa", province: "Samut Songkhram")
PostalCode.create(number_code: "75120", city: "Bang Khonthi", province: "Samut Songkhram")
PostalCode.create(number_code: "67000", city: "Muang Phetchabun", province: "Phetchabun")
PostalCode.create(number_code: "67110", city: "Lom Sak", province: "Phetchabun")
PostalCode.create(number_code: "67120", city: "Lom Kao", province: "Phetchabun")
PostalCode.create(number_code: "67130", city: "Wichian Buri", province: "Phetchabun")
PostalCode.create(number_code: "67140", city: "Nong Phai", province: "Phetchabun")
PostalCode.create(number_code: "67150", city: "Chon Daen", province: "Phetchabun")
PostalCode.create(number_code: "67160", city: "Bung Sam Phan", province: "Phetchabun")
PostalCode.create(number_code: "67170", city: "Si Thep", province: "Phetchabun")
PostalCode.create(number_code: "67240", city: "Wang Pong", province: "Phetchabun")
PostalCode.create(number_code: "67260", city: "Nam Nao", province: "Phetchabun")
PostalCode.create(number_code: "67270", city: "Khao Kho", province: "Phetchabun")
PostalCode.create(number_code: "76000", city: "Muang Phetchaburi", province: "Phetchaburi")
PostalCode.create(number_code: "76110", city: "Ban Laem", province: "Phetchaburi")
PostalCode.create(number_code: "76120", city: "Cha-Am", province: "Phetchaburi")
PostalCode.create(number_code: "76130", city: "Tha Yang", province: "Phetchaburi")
PostalCode.create(number_code: "76140", city: "Khao Yoi", province: "Phetchaburi")
PostalCode.create(number_code: "76150", city: "Ban Lat", province: "Phetchaburi")
PostalCode.create(number_code: "76160", city: "Nong Ya Plong", province: "Phetchaburi")
PostalCode.create(number_code: "76170", city: "Kang Krachan", province: "Phetchaburi")
PostalCode.create(number_code: "81000", city: "Muang Krabi", province: "Krabi")
PostalCode.create(number_code: "81110", city: "Ao Luk", province: "Krabi")
PostalCode.create(number_code: "81120", city: "Khlong Thom", province: "Krabi")
PostalCode.create(number_code: "81130", city: "Nua Khlong", province: "Krabi")
PostalCode.create(number_code: "81140", city: "Khao Phanom", province: "Krabi")
PostalCode.create(number_code: "81150", city: "Ko Lanta", province: "Krabi")
PostalCode.create(number_code: "81160", city: "Plai Phraya", province: "Krabi")
PostalCode.create(number_code: "82000", city: "Muang Phang Nga", province: "Phang Nga")
PostalCode.create(number_code: "82110", city: "Takua Pa", province: "Phang Nga")
PostalCode.create(number_code: "82120", city: "Thai Muang", province: "Phang Nga")
PostalCode.create(number_code: "82130", city: "Takua Thung", province: "Phang Nga")
PostalCode.create(number_code: "82150", city: "Khura Buri", province: "Phang Nga")
PostalCode.create(number_code: "82160", city: "Koh Yao", province: "Phang Nga")
PostalCode.create(number_code: "82170", city: "Kapong", province: "Phang Nga")
PostalCode.create(number_code: "82180", city: "Thap Put", province: "Phang Nga")
PostalCode.create(number_code: "83000", city: "Muang Phuket", province: "Phuket")
PostalCode.create(number_code: "83110", city: "Thalang", province: "Phuket")
PostalCode.create(number_code: "83120", city: "Kathu", province: "Phuket")
PostalCode.create(number_code: "84000", city: "Muang Surat Thani", province: "Surat Thani")
PostalCode.create(number_code: "84110", city: "Chaiya", province: "Surat Thani")
PostalCode.create(number_code: "84120", city: "Ban Na San", province: "Surat Thani")
PostalCode.create(number_code: "84130", city: "Phunphin", province: "Surat Thani")
PostalCode.create(number_code: "84140", city: "Ko Samui", province: "Surat Thani")
PostalCode.create(number_code: "84150", city: "Tha Chang", province: "Surat Thani")
PostalCode.create(number_code: "84160", city: "Kanchanadit", province: "Surat Thani")
PostalCode.create(number_code: "84170", city: "Tha Chana", province: "Surat Thani")
PostalCode.create(number_code: "84180", city: "Wiphawadi", province: "Surat Thani")
PostalCode.create(number_code: "84190", city: "Wiang Sa", province: "Surat Thani")
PostalCode.create(number_code: "84210", city: "Chai Buri", province: "Surat Thani")
PostalCode.create(number_code: "84220", city: "Don Sak", province: "Surat Thani")
PostalCode.create(number_code: "84230", city: "Ban Ta Khun", province: "Surat Thani")
PostalCode.create(number_code: "84240", city: "Ban Na Doem", province: "Surat Thani")
PostalCode.create(number_code: "84250", city: "Phanom", province: "Surat Thani")
PostalCode.create(number_code: "84260", city: "Khian Sa", province: "Surat Thani")
PostalCode.create(number_code: "84280", city: "Ko Phangan", province: "Surat Thani")
PostalCode.create(number_code: "85000", city: "Muang Ranong", province: "Ranong")
PostalCode.create(number_code: "85110", city: "Kra Buri", province: "Ranong")
PostalCode.create(number_code: "85120", city: "Kapoe", province: "Ranong")
PostalCode.create(number_code: "85130", city: "La-Un", province: "Ranong")
PostalCode.create(number_code: "90000", city: "Muang Songkhla", province: "Songkhla")
PostalCode.create(number_code: "90110", city: "Bang Klam", province: "Songkhla")
PostalCode.create(number_code: "90120", city: "Sa Dao", province: "Songkhla")
PostalCode.create(number_code: "90130", city: "Chana", province: "Songkhla")
PostalCode.create(number_code: "90140", city: "Ranot", province: "Songkhla")
PostalCode.create(number_code: "90150", city: "Thepha", province: "Songkhla")
PostalCode.create(number_code: "90160", city: "Na Thawi", province: "Songkhla")
PostalCode.create(number_code: "90180", city: "Rattapum", province: "Songkhla")
PostalCode.create(number_code: "90190", city: "Sating Phra", province: "Songkhla")
PostalCode.create(number_code: "90210", city: "Sabayoi", province: "Songkhla")
PostalCode.create(number_code: "90220", city: "Kuan Niang", province: "Songkhla")
PostalCode.create(number_code: "90230", city: "Khlong Hoykhong", province: "Songkhla")
PostalCode.create(number_code: "90270", city: "Krasae Sin", province: "Songkhla")
PostalCode.create(number_code: "90310", city: "Na Mom", province: "Songkhla")
PostalCode.create(number_code: "90330", city: "Singha Nakorn", province: "Songkhla")
PostalCode.create(number_code: "91000", city: "Muang Satun", province: "Satun")
PostalCode.create(number_code: "91110", city: "Langu", province: "Satun")
PostalCode.create(number_code: "91120", city: "Thung Wa", province: "Satun")
PostalCode.create(number_code: "91130", city: "Manung", province: "Satun")
PostalCode.create(number_code: "91150", city: "Tha Phae", province: "Satun")
PostalCode.create(number_code: "91160", city: "Khuan Doan", province: "Satun")
PostalCode.create(number_code: "92000", city: "Muang Trang", province: "Trang")
PostalCode.create(number_code: "92110", city: "Kantang", province: "Trang")
PostalCode.create(number_code: "92120", city: "Had Samran", province: "Trang")
PostalCode.create(number_code: "92130", city: "Huai Yot", province: "Trang")
PostalCode.create(number_code: "92140", city: "Yan Tak Kao", province: "Trang")
PostalCode.create(number_code: "92150", city: "Sikao", province: "Trang")
PostalCode.create(number_code: "92160", city: "Rachada", province: "Trang")
PostalCode.create(number_code: "92170", city: "Na Yong", province: "Trang")
PostalCode.create(number_code: "92220", city: "Wang Wiset", province: "Trang")
PostalCode.create(number_code: "94000", city: "Muang Pattani", province: "Pattani")
PostalCode.create(number_code: "94110", city: "Sai Buri", province: "Pattani")
PostalCode.create(number_code: "94120", city: "Khok Pho", province: "Pattani")
PostalCode.create(number_code: "94130", city: "Panare", province: "Pattani")
PostalCode.create(number_code: "94140", city: "Thung Yan Daeng", province: "Pattani")
PostalCode.create(number_code: "94150", city: "Yaring", province: "Pattani")
PostalCode.create(number_code: "94160", city: "Yarang", province: "Pattani")
PostalCode.create(number_code: "94170", city: "Nong Chik", province: "Pattani")
PostalCode.create(number_code: "94180", city: "Mae Lan", province: "Pattani")
PostalCode.create(number_code: "94220", city: "Mai Kaen", province: "Pattani")
PostalCode.create(number_code: "94230", city: "Kpho", province: "Pattani")
PostalCode.create(number_code: "95000", city: "Muang Yala", province: "Yala")
PostalCode.create(number_code: "95110", city: "Betong", province: "Yala")
PostalCode.create(number_code: "95120", city: "Ka Bung", province: "Yala")
PostalCode.create(number_code: "95130", city: "Bannang Sata", province: "Yala")
PostalCode.create(number_code: "95140", city: "Raman", province: "Yala")
PostalCode.create(number_code: "95150", city: "Than To", province: "Yala")
PostalCode.create(number_code: "96000", city: "Muang Narathiwat", province: "Narathiwat")
PostalCode.create(number_code: "96110", city: "Tak Bai", province: "Narathiwat")
PostalCode.create(number_code: "96120", city: "Sungai Kolok", province: "Narathiwat")
PostalCode.create(number_code: "96130", city: "Rangae", province: "Narathiwat")
PostalCode.create(number_code: "96140", city: "Sungai Padi", province: "Narathiwat")
PostalCode.create(number_code: "96150", city: "Ruso", province: "Narathiwat")
PostalCode.create(number_code: "96160", city: "Waeng", province: "Narathiwat")
PostalCode.create(number_code: "96170", city: "Bacho", province: "Narathiwat")
PostalCode.create(number_code: "96180", city: "Yi-Ngo", province: "Narathiwat")
PostalCode.create(number_code: "96190", city: "Sukhirin", province: "Narathiwat")
PostalCode.create(number_code: "96210", city: "Si Sakhon", province: "Narathiwat")
PostalCode.create(number_code: "96220", city: "Chanae", province: "Narathiwat")
PostalCode.create(number_code: "13000", city: "Pharnakhon Si Ayutthaya", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13110", city: "Sena", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13120", city: "Pak Hai", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13130", city: "Tha Rua", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13140", city: "Phachi", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13150", city: "Maha Rat", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13160", city: "Bang Pa-In", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13170", city: "Wang Noi", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13190", city: "Bang Sai", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13210", city: "Uthai", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13220", city: "Bang Pahan", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13230", city: "Lat Bua Luang", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13240", city: "Ban Phraek", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13250", city: "Bang Ban", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13260", city: "Nakhon Luang", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "13270", city: "Bang Sai", province: "Phranakhon Si Ayutthaya")
PostalCode.create(number_code: "15000", city: "Muang Lopburi", province: "Lopburi")
PostalCode.create(number_code: "15110", city: "Ban Mi", province: "Lopburi")
PostalCode.create(number_code: "15120", city: "Khok Samrong", province: "Lopburi")
PostalCode.create(number_code: "15130", city: "Chai Badan", province: "Lopburi")
PostalCode.create(number_code: "15140", city: "Phattana Nikhom", province: "Lopburi")
PostalCode.create(number_code: "15150", city: "Tha Wung", province: "Lopburi")
PostalCode.create(number_code: "15170", city: "Nong Muang", province: "Lopburi")
PostalCode.create(number_code: "15190", city: "Lum Sunthi", province: "Lopburi")
PostalCode.create(number_code: "15240", city: "Sa Bot", province: "Lopburi")
PostalCode.create(number_code: "15250", city: "Khok Charoen", province: "Lopburi")
PostalCode.create(number_code: "16000", city: "Muang Sing Buri", province: "Singburi")
PostalCode.create(number_code: "16110", city: "In Buri", province: "Singburi")
PostalCode.create(number_code: "16120", city: "Phrom Buri", province: "Singburi")
PostalCode.create(number_code: "16130", city: "Bang Rachan", province: "Singburi")
PostalCode.create(number_code: "16140", city: "Tha Chang", province: "Singburi")
PostalCode.create(number_code: "16150", city: "Khai Bang Rachan", province: "Singburi")
PostalCode.create(number_code: "17000", city: "Muang Chainat", province: "Chainat")
PostalCode.create(number_code: "17100", city: "Nong Mamong", province: "Chainat")
PostalCode.create(number_code: "17110", city: "Manorom", province: "Chainat")
PostalCode.create(number_code: "17120", city: "Wat Sing", province: "Chainat")
PostalCode.create(number_code: "17130", city: "Non Kham", province: "Chainat")
PostalCode.create(number_code: "17140", city: "Sankhaburi", province: "Chainat")
PostalCode.create(number_code: "17150", city: "Sanphaya", province: "Chainat")
PostalCode.create(number_code: "20000", city: "Muang Chonburi", province: "Chonburi")
PostalCode.create(number_code: "20110", city: "Si Racha", province: "Chonburi")
PostalCode.create(number_code: "20120", city: "Ko Sichang", province: "Chonburi")
PostalCode.create(number_code: "20140", city: "Phanat Nikhom", province: "Chonburi")
PostalCode.create(number_code: "20150", city: "Bang Lamung", province: "Chonburi")
PostalCode.create(number_code: "20160", city: "Phan Thong", province: "Chonburi")
PostalCode.create(number_code: "20170", city: "Ban Bung", province: "Chonburi")
PostalCode.create(number_code: "20180", city: "Sattahip", province: "Chonburi")
PostalCode.create(number_code: "20190", city: "Nong Yai", province: "Chonburi")
PostalCode.create(number_code: "20240", city: "Ko Chan", province: "Chonburi")
PostalCode.create(number_code: "20270", city: "Bo Thong", province: "Chonburi")
PostalCode.create(number_code: "25000", city: "Muang Prachinburi", province: "Prachinburi")
PostalCode.create(number_code: "25110", city: "Kabin Buri", province: "Prachinburi")
PostalCode.create(number_code: "25130", city: "Prachantakham", province: "Prachinburi")
PostalCode.create(number_code: "25140", city: "Si Maha Phot", province: "Prachinburi")
PostalCode.create(number_code: "25150", city: "Ban Sang", province: "Prachinburi")
PostalCode.create(number_code: "25190", city: "Khok Pip", province: "Prachinburi")
PostalCode.create(number_code: "25220", city: "Na Di", province: "Prachinburi")
PostalCode.create(number_code: "31000", city: "Ban Dan", province: "Burirum")
PostalCode.create(number_code: "31110", city: "Nang Rong", province: "Burirum")
PostalCode.create(number_code: "31120", city: "Phutthaisong", province: "Burirum")
PostalCode.create(number_code: "31130", city: "Lam Phai Mat", province: "Burirum")
PostalCode.create(number_code: "31140", city: "Prakhon Chai", province: "Burirum")
PostalCode.create(number_code: "31150", city: "Kandong", province: "Burirum")
PostalCode.create(number_code: "31160", city: "Krasang", province: "Burirum")
PostalCode.create(number_code: "31170", city: "Lahan Sai", province: "Burirum")
PostalCode.create(number_code: "31180", city: "Ban Kruat", province: "Burirum")
PostalCode.create(number_code: "31190", city: "Khu Muang", province: "Burirum")
PostalCode.create(number_code: "31210", city: "Nong Ki", province: "Burirum")
PostalCode.create(number_code: "31220", city: "Pak Kam", province: "Burirum")
PostalCode.create(number_code: "31230", city: "Na Pho", province: "Burirum")
PostalCode.create(number_code: "31240", city: "Nong Hong", province: "Burirum")
PostalCode.create(number_code: "31250", city: "Ban Phlapphla", province: "Burirum")
PostalCode.create(number_code: "31260", city: "Non Dindaeng", province: "Burirum")
PostalCode.create(number_code: "33000", city: "Muang Sisaket", province: "Sisaket")
PostalCode.create(number_code: "33110", city: "Kantharalak", province: "Sisaket")
PostalCode.create(number_code: "33120", city: "Po Sri Suwan", province: "Sisaket")
PostalCode.create(number_code: "33130", city: "Nam Kliang", province: "Sisaket")
PostalCode.create(number_code: "33140", city: "Khukhan", province: "Sisaket")
PostalCode.create(number_code: "33150", city: "Khun Han", province: "Sisaket")
PostalCode.create(number_code: "33160", city: "Silalad", province: "Sisaket")
PostalCode.create(number_code: "33170", city: "Prang Ku", province: "Sisaket")
PostalCode.create(number_code: "33180", city: "Phrai Bung", province: "Sisaket")
PostalCode.create(number_code: "33190", city: "Yang Chum Noi", province: "Sisaket")
PostalCode.create(number_code: "33210", city: "Huai Thap Than", province: "Sisaket")
PostalCode.create(number_code: "33220", city: "Bung Bun", province: "Sisaket")
PostalCode.create(number_code: "33230", city: "Phayu", province: "Sisaket")
PostalCode.create(number_code: "33240", city: "Si Rattana", province: "Sisaket")
PostalCode.create(number_code: "33250", city: "Non Khun", province: "Sisaket")
PostalCode.create(number_code: "33270", city: "Wang Hin", province: "Sisaket")
PostalCode.create(number_code: "34110", city: "Phibun Mangsahan", province: "Na Tan")
PostalCode.create(number_code: "34130", city: "Trakan Puetphon", province: "Na Tan")
PostalCode.create(number_code: "34190", city: "Sawang Werarong", province: "Na Tan")
PostalCode.create(number_code: "34250", city: "Si Muang Mai", province: "Na Tan")
PostalCode.create(number_code: "34260", city: "Nam Khun", province: "Na Tan")
PostalCode.create(number_code: "34330", city: "Tan Sum", province: "Na Tan")
PostalCode.create(number_code: "34340", city: "Po Sai", province: "Na Tan")
PostalCode.create(number_code: "34350", city: "Sirinhon", province: "Na Tan")
PostalCode.create(number_code: "34360", city: "Samrong", province: "Na Tan")
PostalCode.create(number_code: "39000", city: "Muang Nong Bua Lam Phu", province: "Non Bua Lam Phu")
PostalCode.create(number_code: "39140", city: "Non Sang", province: "Non Bua Lam Phu")
PostalCode.create(number_code: "39170", city: "Na Klang", province: "Non Bua Lam Phu")
PostalCode.create(number_code: "39180", city: "Si Bun Ruang", province: "Non Bua Lam Phu")
PostalCode.create(number_code: "39270", city: "Suwannakhuha", province: "Non Bua Lam Phu")
PostalCode.create(number_code: "71000", city: "Muang Kanchanaburi", province: "Khanchanaburi")
PostalCode.create(number_code: "71110", city: "Tha Muang", province: "Khanchanaburi")
PostalCode.create(number_code: "71120", city: "Tha Maka", province: "Khanchanaburi")
PostalCode.create(number_code: "71140", city: "Phanom Thuan", province: "Khanchanaburi")
PostalCode.create(number_code: "71150", city: "Sai Yok", province: "Khanchanaburi")
PostalCode.create(number_code: "71160", city: "Bo Phloi", province: "Khanchanaburi")
PostalCode.create(number_code: "71170", city: "Huai Khaiaw", province: "Khanchanaburi")
PostalCode.create(number_code: "71180", city: "Thong Phaphum", province: "Khanchanaburi")
PostalCode.create(number_code: "71210", city: "Lao Khwan", province: "Khanchanaburi")
PostalCode.create(number_code: "71220", city: "Nong Prue", province: "Khanchanaburi")
PostalCode.create(number_code: "71240", city: "Sangkhla Buri", province: "Khanchanaburi")
PostalCode.create(number_code: "71250", city: "Si Sawat", province: "Khanchanaburi")
PostalCode.create(number_code: "71260", city: "Dan Makham Tia", province: "Khanchanaburi")
PostalCode.create(number_code: "77000", city: "Muang prachuap Khirikan", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77110", city: "Hua Hin", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77120", city: "Pran Buri", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77130", city: "Thap Sakae", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77140", city: "Bang Saphan", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77150", city: "Kui Buri", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77170", city: "Bang Saphan Noi", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "77180", city: "Samaroiyod", province: "Prachuap Khirikhan")
PostalCode.create(number_code: "80000", city: "Phra Phrom", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80110", city: "Thung Song", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80120", city: "Sichon", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80130", city: "Ron Phibun", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80140", city: "Pak Phanang", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80150", city: "Chawang", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80160", city: "Nob Pitam", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80170", city: "Hua Sai", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80180", city: "Cha-uat", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80190", city: "Chian Yai", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80210", city: "Khanom", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80220", city: "Na Bon", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80230", city: "Lan Saka", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80240", city: "Thung Yai", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80250", city: "Chang Khlang", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80260", city: "Tham Punnara", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80270", city: "Phipun", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80320", city: "Phromkhiri", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "80360", city: "Bang Khan", province: "Nakhon Sie Thammarat")
PostalCode.create(number_code: "86000", city: "Muang Chumphon", province: "Chumphon")
PostalCode.create(number_code: "86110", city: "Lang Suan", province: "Chumphon")
PostalCode.create(number_code: "86130", city: "Sawi", province: "Chumphon")
PostalCode.create(number_code: "86140", city: "Tha Sae", province: "Chumphon")
PostalCode.create(number_code: "86160", city: "Pathiu", province: "Chumphon")
PostalCode.create(number_code: "86170", city: "Lamae", province: "Chumphon")
PostalCode.create(number_code: "86180", city: "Phato", province: "Chumphon")
PostalCode.create(number_code: "86220", city: "Thung Tako", province: "Chumphon")
PostalCode.create(number_code: "93000", city: "Sri Nakharin", province: "Phatthalung")
PostalCode.create(number_code: "93110", city: "Pa Payam", province: "Phatthalung")
PostalCode.create(number_code: "93120", city: "Pak Phayun", province: "Phatthalung")
PostalCode.create(number_code: "93130", city: "Khao Chaison", province: "Phatthalung")
PostalCode.create(number_code: "93140", city: "Bang Kaeo", province: "Phatthalung")
PostalCode.create(number_code: "93160", city: "Tamot", province: "Phatthalung")
PostalCode.create(number_code: "93170", city: "Pa Bon", province: "Phatthalung")
PostalCode.create(number_code: "93180", city: "Kong Ra", province: "Phatthalung")
PostalCode.create(number_code: "93190", city: "Si Ban Phot", province: "Phatthalung")

